// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx7pEqv6fUZVu9q9js9b7mM_qI79OyAK8',
    appId: '1:886214558305:web:d217f2ed33f3eea427e020',
    messagingSenderId: '886214558305',
    projectId: 'being-u',
    authDomain: 'being-u.firebaseapp.com',
    storageBucket: 'being-u.appspot.com',
    measurementId: 'G-YHRTJWPBFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqCJ30N_XI4T-IbOQRYs4reomFUr22jBY',
    appId: '1:886214558305:android:ec2a339ba3af874327e020',
    messagingSenderId: '886214558305',
    projectId: 'being-u',
    storageBucket: 'being-u.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOkuRzq9hsrOhorENOXkKx5Fl8_YpcRc4',
    appId: '1:886214558305:ios:907a4bc2be3d003e27e020',
    messagingSenderId: '886214558305',
    projectId: 'being-u',
    storageBucket: 'being-u.appspot.com',
    androidClientId: '886214558305-okdhd1r3csg4mlcbqir66dhpd725912m.apps.googleusercontent.com',
    iosClientId: '886214558305-0vrvhg5j329o6not6g74ovmael2mm22d.apps.googleusercontent.com',
    iosBundleId: 'com.srivats.beingu',
  );
}
